### ISSUE TITLE
standardizing object and string objects

### ISSUE THREAD

**Issue by az0977776** [maxtcruz/cs4500-a1-part2#3]
Can we try to just use the definitions of string and object that Jan provided us:
https://piazza.com/class/k51bluky59n2jr?cid=330

https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by seanolly** [comment]
the interfaces for both string & object should match now, LMK if there's anything left out

**Comment by jessica-cheng** [comment]
Can we get rid of toString? My other spec groups don't have it and I don't really see why we need it?

**Comment by jessica-cheng** [comment]
You don't have toString in your test-queue.cpp anyways

**Comment by seanolly** [comment]
sure

**Comment by maxtcruz** [comment]
done.
