### ISSUE TITLE
Remove delete statements in tests

### ISSUE THREAD

**Issue by jessica-cheng** [maxtcruz/cs4500-a1-part2#7]
I don't think it is necessary to call delete at the end of each test. The destructor is run whenever an object goes out of scope.

**Comment by seanolly** [comment]
C++/C/CwC is not a garbage collected language, when you allocate memory on the heap via the "new" keyword, it needs to be deleted at some point by the user otherwise it is a memory leak

**Comment by jessica-cheng** [comment]
Okay, I do see your point. This was not a consideration we had in our tests so thank you for clarifying
