### ISSUE TITLE
queue constructor

### ISSUE THREAD

**Issue by barthch** [maxtcruz/cs4500-a1-part2#9]
https://github.com/maxtcruz/cs4500-a1-part2/blob/9324da4ec4c57c4d29b029e65a8614d45fd344d3/queue.h#L16
https://github.com/maxtcruz/cs4500-a1-part2/blob/9324da4ec4c57c4d29b029e65a8614d45fd344d3/queue.h#L17

What does this mean? A queue only grows in size if something is added to it. Specifying the capacity of the queue makes sense if the implementation is a check and re-allocate on add, but not if the implementation is something else.

**Comment by maxtcruz** [comment]
I agree with you that this constructor depends on internal implementation. Removed.
